"use client";

import { useEffect, useState } from "react";
import { ArrowRight, CalendarDays, Check, ChevronDown, ChevronRight, Dumbbell, Sparkles, Target } from "lucide-react";
import { PageHeading } from "@/components/dashboard/page-heading";
import { useDashboard } from "../dashboard-provider";
import { canAccess, useFeatureAccess } from "../shared";

interface TrainingPlanData {
  id: string;
  title: string;
  description: string;
  category: string;
  difficulty: string;
  duration_weeks: number;
  sessions_per_week: number;
  status: string;
  current_week: number;
  progress: number;
  total_sessions: number;
  completed_sessions: number;
  is_ai_generated: boolean;
  target_outcome: string | null;
}

export default function PlansPage() {
  const { user, setToast } = useDashboard();
  const { hasAccess, upgradeMessage } = useFeatureAccess("aiWorkoutPlans");
  const [trainingPlans, setTrainingPlans] = useState<TrainingPlanData[]>([]);
  const [plansLoading, setPlansLoading] = useState(false);

  useEffect(() => {
    if (!user) return;
    let active = true;
    setPlansLoading(true);
    const userId = user.id;
    async function loadPlans() {
      try {
        const response = await fetch(`/api/training-plans?userId=${userId}`);
        if (!response.ok) return;
        const data = await response.json();
        if (active) setTrainingPlans(data.plans || []);
      } catch {
        // silent
      } finally {
        if (active) setPlansLoading(false);
      }
    }
    void loadPlans();
    return () => { active = false; };
  }, [user]);

  if (!hasAccess) {
    return (
      <div className="feature-locked">
        <div className="feature-locked-icon"><Sparkles size={32} /></div>
        <h2>Unlock AI Workout Plans</h2>
        <p>Get personalized training plans generated by AI based on your goals, schedule, and progress.</p>
        <ul className="feature-locked-benefits">
          <li><Check size={16} /> Custom plans tailored to your level</li>
          <li><Check size={16} /> Adaptive progression as you improve</li>
          <li><Check size={16} /> Unlimited plan variations</li>
        </ul>
        <button
          className="primary-button"
          onClick={() => setToast("Choose Pro or Elite to unlock AI Workout Plans")}
        >
          <Sparkles size={14} /> Upgrade to Pro
        </button>
      </div>
    );
  }

  return (
    <>
      <PageHeading
        eyebrow="Find your rhythm"
        title="Training plans"
        description="A little structure, with plenty of room to make it yours."
        action={<button className="secondary-button" onClick={() => setToast("More training plans are on the way.")}><Sparkles size={14} /> Generate AI plan</button>}
      />

      {trainingPlans.length === 0 && (
        <div className="generate-prompt">
          <Sparkles size={24} />
          <h3>Create your first AI-powered training plan</h3>
          <p>Tell us about your goals and we'll build a personalized program for you.</p>
          <button className="primary-button" onClick={() => setToast("AI plan generation coming soon!")}>
            <Sparkles size={14} /> Generate My Plan
          </button>
        </div>
      )}

      <div className="section-toolbar">
        <h2>Your programs</h2>
        <span className="page-subtitle">Pick up right where you left off.</span>
      </div>

      {plansLoading ? (
        <div className="empty-state">Loading your training plans...</div>
      ) : trainingPlans.length > 0 ? (
        <div className="program-grid">
          {trainingPlans.map((program) => (
            <article className="program-card" key={program.id}>
              <div className="program-top">
                <span className="template-icon"><Target size={17} /></span>
                <span className="program-status">{program.status === "active" ? "In progress" : program.status}</span>
                {program.is_ai_generated && <span className="ai-badge">AI</span>}
              </div>
              <h3>{program.title}</h3>
              <p>{program.description}</p>
              <div className="program-metrics">
                <span className="plan-metric"><CalendarDays size={13} /> Week {program.current_week} of {program.duration_weeks}</span>
                <span className="plan-metric"><Dumbbell size={13} /> {program.sessions_per_week} sessions / week</span>
                <span className="plan-metric"><Check size={13} /> {program.completed_sessions} of {program.total_sessions} complete</span>
              </div>
              <div className="program-progress"><span style={{ width: `${program.progress}%` }} /></div>
              <div className="program-footer">
                <span>{program.progress}%</span>
                {program.progress < 100 && (
                  <button className="text-button" onClick={() => setToast("Continue your plan")}>
                    Continue <ArrowRight size={12} />
                  </button>
                )}
              </div>
            </article>
          ))}
        </div>
      ) : (
        <div className="empty-state" style={{ textAlign: "center", padding: "40px" }}>
          <CalendarDays size={48} strokeWidth={1.5} />
          <h3>No training plans yet</h3>
          <p>Generate an AI-powered plan tailored to your goals, or create a custom plan manually.</p>
          <button
            className="primary-button"
            style={{ marginTop: "16px" }}
            onClick={() => setToast("AI plan generation coming soon!")}
          >
            <Sparkles size={14} /> Generate AI Plan
          </button>
        </div>
      )}
    </>
  );
}
